---
- name: CONTAINER INFLUXDB // CREATING FOLDER 
  file:
      dest: "{{ docker.path_to_containers }}/influxdb"
      state: directory
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // CREATING STORAGE FOLDER
  file:
      dest: "{{ docker.path_to_containers }}/influxdb/data"
      state: directory
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // GENERATING INFLUXDB CONFIG
  shell: "docker run --rm influxdb influxd config > {{ docker.path_to_containers }}/influxdb/influxdb.conf"
  become: yes
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // LAUNCHING CONTAINER
  docker_container:
      name: dcf_influxdb
      image: influxdb
      state: started
      command: "-config /etc/influxdb/influxdb.conf"
      networks:
          - name: "{{ docker.private_network.name }}"
      purge_networks: yes
      ports:
          - "8086:8086"
      volumes:
          - "{{ pwd_actual }}/{{ docker.path_to_containers }}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
          - "{{ pwd_actual }}/{{ docker.path_to_containers }}/influxdb/data:/var/lib/influxdb"
  become: yes
  tags:
      - tick_install
      - tick_ops

- name: CONTAINER INFLUXDB // WAITING CONTAINER TO BOOT
  pause:
      seconds: 15
  tags:
      - tick_install
      - tick_ops

- name: CONTAINER INFLUXDB // CREATING DATABASE FOR SNMP
  uri:
      url: "http://localhost:8086/query?q={{ db_request | urlencode }}"
      method: POST
  ignore_errors: yes
  vars:
      db_request: "CREATE DATABASE {{ var_influxdb.db_name.snmp }}"
  tags:
      - tick_install
 
- name: CONTAINER INFLUXDB // CREATING DATABASE FOR SYSLOG
  uri:
      url: "http://localhost:8086/query?q={{ db_request | urlencode }}"
      method: POST
  ignore_errors: yes
  vars:
      db_request: "CREATE DATABASE {{ var_influxdb.db_name.syslog }}"
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // CREATING USERS
  uri:
      url: "http://localhost:8086/query?q={{ db_request | urlencode }}"
      method: POST
  ignore_errors: yes
  vars:
      db_request: "CREATE USER {{ var_influxdb.username }} WITH PASSWORD '{{ var_influxdb.password }}' WITH ALL PRIVILEGES"
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // GENERATING SSL CERTIFICATE
  shell: 'docker exec -i dcf_influxdb openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/ssl/influxdb-selfsigned.key -out /etc/ssl/influxdb-selfsigned.crt -days 365 -subj "/C=DE/ST=NRW/L=DUS/O=karneliuk.com/CN=influxdb.karneliuk.com"'
  become: yes
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // ENABLING AUTHENTICATION
  lineinfile:
      dest: "{{ docker.path_to_containers }}/influxdb/influxdb.conf"
      regexp: 'auth-enabled = false'
      line: 'auth-enabled = true'
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // ENABLING HTTPS
  lineinfile:
      dest: "{{ docker.path_to_containers }}/influxdb/influxdb.conf"
      regexp: 'https-enabled = false'
      line: 'https-enabled = true'
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // PROVIDING CERTIFICATE PATH
  lineinfile:
      dest: "{{ docker.path_to_containers }}/influxdb/influxdb.conf"
      regexp: 'https-certificate = "/etc/ssl/influxdb.pem"'
      line: 'https-certificate = "/etc/ssl/influxdb-selfsigned.crt"'
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // PROVIDING KEY PATH
  lineinfile:
      dest: "{{ docker.path_to_containers }}/influxdb/influxdb.conf"
      regexp: 'https-private-key = ""'
      line: 'https-private-key = "/etc/ssl/influxdb-selfsigned.key"'
  tags:
      - tick_install

- name: CONTAINER INFLUXDB // RESTARTING CONTAINER
  docker_container:
      name: dcf_influxdb
      image: influxdb
      state: started
      restart: yes
      command: "-config /etc/influxdb/influxdb.conf"
      networks:
          - name: "{{ docker.private_network.name }}"
      purge_networks: yes
      ports:
           - "8086:8086"
      volumes:
           - "{{ pwd_actual }}/{{ docker.path_to_containers }}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
           - "{{ pwd_actual }}/{{ docker.path_to_containers }}/influxdb/data:/var/lib/influxdb"
  become: yes
  tags:
      - tick_install
...
